services:
  - type: web
    name: pothole-detector-week1
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd pothole_webapp
    startCommand: cd pothole_webapp && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2