services:
  - type: web
    name: pothole-detector-week1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pothole_webapp.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
